<?php 
    $this->headTitle('Company | Grizzly Cubs Den');
?>


<div class="about-banner-container">
    <div class="container">
        <h2 class="about-message banner-message text-center">Meet the Grizzly Cubs Team</h2>
    </div>
</div>
<div class="about-content-container container">
    <h1 class="about-us-heading blue text-center">ABOUT US</h1>
    <p class="about-us-text">
        Grizzly Cubs Den is the newest and most creative indoor playground located in Leduc and we
        are happy to welcome families and individuals from other neighbouring areas including
        Edmonton and Beaumont.
    </p>
    <p class="about-us-text">
        We offer our own designed Play Town. We are excited to share with you our imaginative play
        area where children can learn, role play and have fun.
    </p>
    <p class="about-us-text">
        Grizzly Cubs Den is also a birthday party venue and a play area designed to stimulate
        children’s minds through exploration and problem solving while they play and imitate the
        adult world.
    </p>
    <p class="about-us-text">
        Besides from being an indoor playground, we also offer children’s classes. Please inquire
        through email, phone or message us on Facebook and Instagram for classes that we offer and
        also for your booking needs and inquiries.
    </p>
    <p class="about-us-text">
        Besides from being an indoor playground, we also offer children’s classes. Please inquire
        through email, phone or message us on Facebook and Instagram for classes that we offer and
        also for your booking needs and inquiries.
    </p>
    <p class="about-us-text">
        Follow us on Facebook and Instagram – Grizzly Cubs Den. The Amazing Indoor Playground to
        keep your children active, sociable, smart and healthy. Let us “Cherish the Moment” with our
        loved ones.
    </p>
    <p class="about-us-text">
        WE WILL ALSO BRING THE LATEST SOCCER SUPER GOALIE THAT WILL CHALLENGE ALL KINDS OF SOCCER
        PLAYERS! FUN FOR THE WHOLE FAMILY
    </p>
</div>
<div class="characters-container container">
    <div class="characters-heading text-center red">
        Your friends at Grizzly Cubs are excited to meet you!
    </div>
    <div class="row characters-row">
        <div class="offset-sm-1 col-sm-3 char-img-wrapper text-center">
            <img class="char-img" src="<?= $this->basePath('images/char-chubs.png') ?>" alt="">
        </div>
        <div class="col-sm-7 char-intro-container">
            <div class="char-greeting red">
                Hi, I’m Cubs!
            </div>
            <p class="char-intro">
                I love soccer!
            </p>
            <p class="char-intro">
                So, I come everyday to Grizzly Cubs Den to try and beat the most popular super
                goalie in town. Brothers, come and join me!
            </p>
        </div>
        <div class="offset-sm-1 col-sm-3 char-img-wrapper text-center">
            <img class="char-img" src="<?= $this->basePath('images/char-maya.png') ?>" alt="">
        </div>
        <div class="col-sm-7 char-intro-container">
            <div class="char-greeting red">
                Hello girls and boys! My name is Maya.
            </div>
            <p class="char-intro">
                I’m Cub’s best friend. We met at Grizzly Cubs Den. I love attending their weekly
                kid’s classes. The classes are super healthy for me, I learned to be more friendly. 
            </p>
        </div>
        <div class="offset-sm-1 col-sm-3 char-img-wrapper text-center">
            <img class="char-img" src="<?= $this->basePath('images/char-javs.png') ?>" alt="">
        </div>
        <div class="col-sm-7 char-intro-container">
            <div class="char-greeting red">
                Meow! I’m Jigs.
            </div>
            <p class="char-intro">
                I love playing and climbing up the playground. I celebrate my birthday at Grizzly
                Cubs Den every year with my friends and they surely have fun!     
            </p>
        </div>
    </div>
</div>