<?php 
    $this->headTitle('Company | Grizzly Cubs Den');
?>


<div class="about-banner-container">
    <div class="container">
        <h2 class="about-message banner-message text-center">Meet the Grizzly Cubs Team</h2>
    </div>
</div>
<div class="about-content-container container">
    <h1 class="about-us-heading blue text-center">ABOUT US</h1>
    <p class="about-us-text">
        Grizzly Cubs Den is the latest indoor playground in Edmonton and Leduc Area that offers our
        own designed Play Town. We are excited to share with you our imaginative play area where
        children can learn, role play and have fun.
    </p>
    <p class="about-us-text">
        Grizzly Cubs Den is an open play area and birthday party venue designed to stimulate children’s
        minds through exploration and problem solving while they play and imitate adults in a small
        community of playhouses.  We also offer ninja and climbing equipment that will burn off your
        kids’ energy and help them stay active.  At Grizzly Cubs Den, children are free to imagine in a
        grown-up world and encourage confidence, learn gross motor skills while allowing them to explore
        and interact with others.
    </p>
    <p class="about-us-text">
        We have the very first wooden sand pit and super soccer goalie that will amaze you. Come
        check them out. Grizzly Cubs Den offers various activities for the whole family.
    </p>
    <p class="about-us-text">
        Our dance and music studio is the best place to jam out during weekday mornings, we offer
        classes for ages 0 to 5 years old. We offer kid friendly songs that will stimulate your
        children’s minds at a young age. Inquire about the different classes that we offer. We would
        be happy to assist you.
    </p>
</div>
<div class="characters-container container">
    <div class="characters-heading text-center red">
        Your friends at Grizzly Cubs are excited to meet you!
    </div>
    <div class="row characters-row">
        <div class="offset-sm-1 col-sm-3 char-img-wrapper text-center">
            <img class="char-img" src="<?= $this->basePath('images/char-chubs.png') ?>" alt="">
        </div>
        <div class="col-sm-7 char-intro-container">
            <div class="char-greeting red">
                Hi, I’m Cubs!
            </div>
            <p class="char-intro">
                I love soccer!
            </p>
            <p class="char-intro">
                So, I come everyday to Grizzly Cubs Den to try and beat the most popular super
                goalie in town. Brothers, come and join me!
            </p>
        </div>
        <div class="offset-sm-1 col-sm-3 char-img-wrapper text-center">
            <img class="char-img" src="<?= $this->basePath('images/char-maya.png') ?>" alt="">
        </div>
        <div class="col-sm-7 char-intro-container">
            <div class="char-greeting red">
                Hello girls and boys! My name is Maya.
            </div>
            <p class="char-intro">
                I’m Chub’s best friend. We met at Grizzly Cubs Den. I love dancing so I come weekly
                to their dance classes. It has been a whole lot of fun!
            </p>
        </div>
        <div class="offset-sm-1 col-sm-3 char-img-wrapper text-center">
            <img class="char-img" src="<?= $this->basePath('images/char-javs.png') ?>" alt="">
        </div>
        <div class="col-sm-7 char-intro-container">
            <div class="char-greeting red">
                Meow! I’m JV.
            </div>
            <p class="char-intro">
                I love playing and climbing up the playground. I celebrate my birthday at Grizzly
                Cubs Den every year with my friends and they surely have fun!     
            </p>
        </div>
    </div>
</div>