<?php 
    $this->headTitle('Birthday Packages | Grizzly Cubs Den');
?>

<div class="birthdays-banner-container container text-center">
    <h2 class="birthdays-message blue banner-message">
        CELEBRATE YOUR BIRTHDAY WITH GRIZZLY CUBS DEN
    </h2>
    <h3 class="birthdays-submessage">
        Just leave it to our friendly party experts!
    </h3>
    <h3 class="birthdays-submessage">
        From 'Hi' to 'Bye', you are in good hands.
    </h3>
    <div class="birthday-btns-wrapper">
        <a href="tel:7808160175" class="call-us-btn primary-btn">CALL US</a>
        <!-- <a class="contact-us-mail" href="mailto:grizzlycubsden@gmail.com"></a> -->
        <a href="mailto:grizzlycubsden@gmail.com" class="email-us-btn primary-btn">EMAIL US</a>
    </div>
</div>
<div class="birthdays-content-container">
    <div class="birthdays-subbanner-container container">
        <div class="birthdays-info-container">
            <h1 class="birthdays-heading blue text-center">Birthday Packages</h1>
            <p class="birthdays-info-text">
                You can bring your own cake or cupcakes, but no other outside food, drink or snacks are
                allowed. We have a cafeteria on site.
            </p>
            <p class="birthdays-info-text">
                OPTIONAL: FACE PAINT / CLOWN
            </p>
            <p class="birthdays-info-text">
                <span class="blue">50%</span> Deposit required at time of booking & non-refundable.
            </p>
        </div>
    </div>
    <div class="birthday-packages-container container">
        <div class="birthday-package">
            <div class="birthday-package-heading">
                <img class="package-heading-img"
                    src="<?= $this->basePath('images/balloon-javs-red.png') ?>"
                    alt="birthday package">
                <span class="package-title off-white">
                    JV Birthday Party Package
                </span>
                <span class="package-price">
                    $285.00 + GST
                </span>
            </div>
            <div class="birthday-package-details">
                <strong class="package-days">
                    (Mondays - Thursdays)    
                </strong>
                <ul class="package-details">
                    <li>
                        10 children admission
                    </li>
                    <li>
                        90 minutes Party Table + UNLIMITED PLAYTIME
                    </li>
                    <li>
                        2 Large Pizza or 10 Hotdogs 
                    </li>
                    <li>
                        1 Platter of Fries
                    </li>
                    <li>
                        2 (2L) of Pop or 10 juice boxes
                    </li>
                    <li>
                        Set Up and Clean Up (You can choose a Theme for the Birthday Sign that we
                        have in stock; Balloons included)
                    </li>
                    <li>
                        Mascot Appearance for Cake Cutting and Pictures
                    </li>
                    <li>
                        Cups, Plates, Cutlery, Napkins and Tablecloth
                    </li>
                    <li>
                        Additional child: $8.95
                    </li>
                </ul>
            </div>
        </div>
        <div class="birthday-package">
            <div class="birthday-package-heading">
                <img class="package-heading-img"
                    src="<?= $this->basePath('images/balloon-maya.png') ?>"
                    alt="birthday package">
                <span class="package-title maya-bday-package">
                    MAYA Birthday Party Package
                </span>
                <span class="package-price">
                    $325.00 + GST
                </span>
            </div>
            <div class="birthday-package-details">
                <strong class="package-days">
                    (Fridays - Sundays)    
                </strong>
                <ul class="package-details">
                    <li>
                        10 children admission
                    </li>
                    <li>
                        90 minutes Party Table + UNLIMITED PLAYTIME
                    </li>
                    <li>
                        2 Large Pizza or 10 Hotdogs 
                    </li>
                    <li>
                        1 Platter of Fries
                    </li>
                    <li>
                        2 (2L) of Pop or 10 juice boxes
                    </li>
                    <li>
                        Set Up and Clean Up (You can choose a Theme for the Birthday Sign that we
                        have in stock; Balloons included)
                    </li>
                    <li>
                        Mascot Appearance for Cake Cutting and Picture 
                    </li>
                    <li>
                        Cups, Plates, Cutlery, Napkins and Tablecloth
                    </li>
                    <li>
                        Additional child: $10.95
                    </li>
                </ul>
            </div>
        </div>
        <div class="birthday-package">
            <div class="birthday-package-heading">
                <img class="package-heading-img"
                    src="<?= $this->basePath('images/balloon-chubs.png') ?>"
                    alt="birthday package">
                <span class="package-title off-white cubs-bday-package">
                    CUBS Birthday Party Package
                </span>
                <span class="package-price">
                    $375.00 + GST
                </span>
            </div>
            <div class="birthday-package-details">
                <strong class="package-days">
                    (Fridays - Sundays)    
                </strong>
                <ul class="package-details">
                    <li>
                        10 children admission
                    </li>
                    <li>
                        90 minutes Party Table + UNLIMITED PLAYTIME
                    </li>
                    <li>
                        2 Large Pizza
                    </li>
                    <li>
                        1 Fruit Platter
                    </li>
                    <li>
                        2 (2L) of Pop or 10 juice Boxes
                    </li>
                    <li>
                        Chicken Strips Platter (12 pcs)
                    </li>
                    <li>
                        Set Up and Clean Up (You can choose a Theme for the Birthday Sign that we
                        have in stock; Balloons included)
                    </li>
                    <li>
                        Mascot Appearance for Cake Cutting and Pictures
                    </li>
                    <li>
                        Cups, Plates, Cutlery, Napkins and Tablecloth
                    </li>
                    <li>
                        Additional child: $10.95
                    </li>
                </ul>
            </div>
        </div>
        <div class="options-notif-container off-white">
            PLEASE ASK ABOUT THE OPTIONS FOR FACE PAINTING, BALLOON SCULPTURE OR A CLOWN TO MAKE
            YOUR LITTLE ONES' BIRTHDAY MORE FUN
        </div>
        <div class="options-notif-container off-white">
            Playground is shared with drop-in play customers.
        </div>
        <div class="options-notif-container off-white">
            PLEASE NOTE:
            <p class="mt-1 mb-0">
                Socks are a MUST (Parents & children inclusive).
            </p>
            <p class="mb-0">
                In case of late arrival, your party still ends at the scheduled time.
            </p>
            <p class="mb-0">
                Time exceeded will result in extra charges ($30/15 mins) in the playground and
                party tables.
            </p>
        </div>
        
    </div>
</div>
<div class="rules-container">
    <h2 class="rules-heading text-center">
        Birthday Party and Events Rules
    </h2>
    <div class="rule-list-container container">
        <ul class="rule-list">
            <li class="rule-list-item">
                The party deposit is 50% must be paid at the time of booking and is non-refundable.
                The balance must be paid before the end of the party. Parties cancelled over 14 days
                prior to the party date will have their deposit available for transfer to another
                date or for use on future admission. 
            </li>
            <li class="rule-list-item">
                Guests should arrive no earlier than 10 minutes prior to the start of the party or
                event. Parents of the birthday celebrant can come 15 minutes earlier.
            </li>
            <li class="rule-list-item">
                You should leave at the end of your party, but if need to extend time please let the
                front desk know. 
            </li>
            <li class="rule-list-item">
                We encourage booking early and coordinating your needs with us. You can always talk
                to us about time, number of guests that you have, additional food order and time
                extension
            </li>
            <li class="rule-list-item">
                We can also accommodate bigger groups for any events and have the premise only for
                your event for specific hours – please talk to us about this option
            </li>
            <li class="rule-list-item">
                Any inquiries, please call us at
                <a href="tel:7808160175">
                    7808160175
                </a>
                or message us on
                <a href="https://www.facebook.com/grizzlycubsden2019/" target="_blank">
                    FACEBOOK
                </a>
                or email us at
                <a href="mailto:grizzlycubsden@gmail.com">
                    grizzlycubsden@gmail.com
                </a>
            </li>
            
        </ul>
    </div>
</div>
<!-- <div class="contact-form-container">
    <div class="container">
        <h3 id="birthdayForm" class="off-white contact-us-heading">
            TELL US MORE ABOUT YOUR EVENT & WE WILL SEND YOUR PERSONALIZED QUOTE TO YOU SOON!
        </h3>
        <form action="" class="contact-form">
            <div class="form-row contact-form-row">
                <div class="col-md-4 contact-name-field">
                    <input type="text" class="form-control contact-field" placeholder="NAME*" maxlength="30">
                </div>
                <div class="col-md-4 contact-phone-field">
                    <input type="number" class="form-control contact-field" placeholder="PHONE*">
                </div>
                <div class="col-md-4">
                    <input type="email" class="form-control contact-field" placeholder="E-MAIL*">
                </div>
            </div>
            <div class="form-row contact-form-row">
                <div class="col-md-4">
                    <input type="text" class="form-control contact-field" placeholder="PREFERRED DAY*">
                </div>
                <div class="col-md-4">
                    <input type="text" class="form-control contact-field" placeholder="PREFERRED TIME*">
                </div>
                <div class="col-md-4">
                    <input type="number" class="form-control contact-field" placeholder="EXPECTED NO. OF PAX*">
                </div>
            </div>
            <div class="contact-form-row">
                <textarea class="form-control contact-field" placeholder="TELL US MORE ABOUT YOUR EVENT" rows="7">
                </textarea>
            </div>
            <div class="send-btn-container">
                <button type="button" class="send-btn btn"
                    onclick="alert('Site Under Construction')">
                    SEND MESSAGE
                </button>
            </div>
        </form>
    </div>
</div> -->