<?php 
    $this->headTitle('Birthday Packages | Grizzly Cubs Den');
?>

<div class="birthdays-banner-container container text-center">
    <h2 class="birthdays-message blue banner-message">
        CELEBRATE YOUR BIRTHDAY WITH GRIZZLY CUBS DEN
    </h2>
    <h3 class="birthdays-submessage">
        Just leave it to our friendly party experts!
    </h3>
    <h3 class="birthdays-submessage">
        From 'Hi' to 'Bye', you are in good hands.
    </h3>
    <div class="birthday-btns-wrapper">
        <a href="tel:7808160175" class="call-us-btn primary-btn">CALL US</a>
        <a href="#birthdayForm" class="email-us-btn primary-btn">EMAIL US</a>
    </div>
</div>
<div class="birthdays-content-container">
    <div class="birthdays-subbanner-container container">
        <div class="birthdays-info-container">
            <h1 class="birthdays-heading blue text-center">Birthday Packages</h1>
            <p class="birthdays-info-text">
                You can bring your own cake or cupcakes, but no other outside food, drink or snacks are
                allowed. We have a cafeteria on site.
            </p>
            <p class="birthdays-info-text">
                OPTIONAL: FACE PAINT / CLOWN
            </p>
            <p class="birthdays-info-text">
                <span class="blue">50%</span> Deposit required at time of booking & non-refundable.
            </p>
        </div>
    </div>
    <div class="birthday-packages-container container">
        <div class="birthday-package">
            <div class="birthday-package-heading">
                <img class="package-heading-img" src="<?= $this->basePath('images/balloon-javs-red.png') ?>" alt="birthday package">
                <span class="package-title off-white">
                    JIGS Birthday Package
                </span>
                <span class="package-price">
                    $275.00 + GST
                </span>
            </div>
            <div class="birthday-package-details">
                <strong class="package-days">
                    (Mondays - Thursdays)    
                </strong>
                <ul class="package-details">
                    <li>10 children admission</li>
                    <li>90 minutes Party Table</li>
                    <li>2 Large Pizza or 10 Hotdogs with a medium Plate of Fries</li>
                    <li>2 Pitchers of Pop</li>
                    <li>Set Up and Cleaning (Birthday Sign and Balloons)</li>
                    <li>Mascot Appearance for Cake Cutting and Pictures</li>
                    <li>Cups, Plates, Cutlery, Napkins and Tablecloth</li>
                    <li>Additional child: $15.95</li>
                </ul>
            </div>
        </div>
        <div class="birthday-package">
            <div class="birthday-package-heading">
                <img class="package-heading-img" src="<?= $this->basePath('images/balloon-maya.png') ?>" alt="birthday package">
                <span class="package-title maya-bday-package">
                    MAYA Birthday Package
                </span>
                <span class="package-price">
                    $345.00 + GST
                </span>
            </div>
            <div class="birthday-package-details">
                <strong class="package-days">
                    (Mondays - Thursdays)    
                </strong>
                <ul class="package-details">
                    <li>10 children admission</li>
                    <li>90 minutes Party Table</li>
                    <li>2 Large Pizza or 10 Hotdogs with a medium Plate of Fries</li>
                    <li>1 Vegetable Platter</li>
                    <li>2 Pitchers of Pop</li>
                    <li>Set Up and Cleaning (Birthday Sign and Balloons)</li>
                    <li>Mascot Appearance for Cake Cutting and Pictures</li>
                    <li>Cups, Plates, Cutlery, Napkins and Tablecloth</li>
                    <li>Additional child: $17.95</li>
                </ul>
            </div>
        </div>
        <div class="birthday-package">
            <div class="birthday-package-heading">
                <img class="package-heading-img" src="<?= $this->basePath('images/balloon-chubs.png') ?>" alt="birthday package">
                <span class="package-title off-white cubs-bday-package">
                    CUBS Birthday Package
                </span>
                <span class="package-price">
                    $395.00 + GST
                </span>
            </div>
            <div class="birthday-package-details">
                <strong class="package-days">
                    (Fridays - Sundays)    
                </strong>
                <ul class="package-details">
                    <li>10 children admission</li>
                    <li>90 minutes Party Table</li>
                    <li>Fruit Platter</li>
                    <li>1 Platter of our "Famouse Nacho Fries"</li>
                    <li>3 Large Pizza</li>
                    <li>3 Pitchers of Pop</li>
                    <li>Set Up and Cleaning (Birthday Sign and Balloons)</li>
                    <li>Mascot Appearance for Cake Cutting and Pictures</li>
                    <li>Cups, Plates, Cutlery, Napkins and Tablecloth</li>
                    <li>Additional child: $18.95</li>
                </ul>
            </div>
        </div>
        <div class="options-notif-container off-white">
            PLEASE ASK ABOUT THE OPTIONS FOR FACE PAINTING, BALLOON SCULPTURE OR A CLOWN TO MAKE
            YOUR LITTLE ONES' BIRTHDAY MORE FUN
        </div>
        <div class="options-notif-container off-white">
            Playground is shared with drop-in play customers.
        </div>
    </div>
</div>
<div class="contact-form-container">
    <div class="container">
        <h3 id="birthdayForm" class="off-white contact-us-heading">
            TELL US MORE ABOUT YOUR EVENT & WE WILL SEND YOUR PERSONALIZED QUOTE TO YOU SOON!
        </h3>
        <form action="" class="contact-form">
            <div class="form-row contact-form-row">
                <div class="col-md-4 contact-name-field">
                    <input type="text" class="form-control contact-field" placeholder="NAME*">
                </div>
                <div class="col-md-4 contact-phone-field">
                    <input type="number" class="form-control contact-field" placeholder="NAME*">
                </div>
                <div class="col-md-4">
                    <input type="email" class="form-control contact-field" placeholder="E-MAIL*">
                </div>
            </div>
            <div class="form-row contact-form-row">
                <div class="col-md-4">
                    <input type="text" class="form-control contact-field" placeholder="PREFERRED DAY*">
                </div>
                <div class="col-md-4">
                    <input type="text" class="form-control contact-field" placeholder="PREFERRED TIME*">
                </div>
                <div class="col-md-4">
                    <input type="number" class="form-control contact-field" placeholder="EXPECTED NO. OF PAX*">
                </div>
            </div>
            <div class="contact-form-row">
                <textarea class="form-control contact-field" placeholder="TELL US MORE ABOUT YOUR EVENT" rows="7"></textarea>
            </div>
            <div class="send-btn-container">
                <button type="button" class="send-btn btn"
                    onclick="alert('Site Under Construction')">
                    SEND MESSAGE
                </button>
            </div>
        </form>
    </div>
</div>