<?php 
    $this->headTitle('Birthday Packages | Grizzly Cubs Den');
?>

<div class="birthdays-banner-container container text-center">
    <h2 class="birthdays-message blue banner-message">
        CELEBRATE YOUR BIRTHDAY WITH GRIZZLY CUBS DEN
    </h2>
    <h3 class="birthdays-submessage">
        Just leave it to our friendly party experts!
    </h3>
    <h3 class="birthdays-submessage">
        From 'Hi' to 'Bye', you are in good hands.
    </h3>
    <div class="birthday-btns-wrapper">
        <a href="tel:7808160175" class="call-us-btn primary-btn">CALL US</a>
        <!-- <a class="contact-us-mail" href="mailto:grizzlycubsden@gmail.com"></a> -->
        <a href="mailto:grizzlycubsden@gmamil.com" class="email-us-btn primary-btn">EMAIL US</a>
    </div>
</div>
<div class="birthdays-content-container">
    <div class="birthdays-subbanner-container container">
        <div class="birthdays-info-container">
            <h1 class="birthdays-heading blue text-center">Birthday Packages</h1>
            <p class="birthdays-info-text">
                You can bring your own cake or cupcakes, but no other outside food, drink or snacks are
                allowed. We have a cafeteria on site.
            </p>
            <p class="birthdays-info-text">
                OPTIONAL: FACE PAINT / CLOWN
            </p>
            <p class="birthdays-info-text">
                <span class="blue">50%</span> Deposit required at time of booking & non-refundable.
            </p>
        </div>
    </div>
    <div class="birthday-packages-container container">
        <!-- <div class="birthday-package">
            <div class="birthday-package-heading">
                <img class="package-heading-img"
                    src="<?= $this->basePath('images/balloon-javs-red.png') ?>"
                    alt="birthday package">
                <span class="package-title off-white">
                    JV Birthday Party Package
                </span>
                <span class="package-price">
                    $285.00 + GST
                </span>
            </div>
            <div class="birthday-package-details">
                <strong class="package-days">
                    (Mondays - Thursdays)    
                </strong>
                <ul class="package-details">
                    <li>
                        10 children admission
                    </li>
                    <li>
                        90 minutes Party Table + UNLIMITED PLAYTIME
                    </li>
                    <li>
                        2 Large Pizza or 10 Hotdogs 
                    </li>
                    <li>
                        1 Platter of Fries
                    </li>
                    <li>
                        2 (2L) of Pop or 10 juice boxes
                    </li>
                    <li>
                        Set Up and Clean Up (You can choose a Theme for the Birthday Sign that we
                        have in stock; Balloons included)
                    </li>
                    <li>
                        Mascot Appearance for Cake Cutting and Pictures
                    </li>
                    <li>
                        Cups, Plates, Cutlery, Napkins and Tablecloth
                    </li>
                    <li>
                        Additional child: $8.95
                    </li>
                </ul>
            </div>
        </div> -->
        <div class="birthday-package">
            <div class="birthday-package-heading">
                <img class="package-heading-img"
                    src="<?= $this->basePath('images/balloon-maya.png') ?>"
                    alt="birthday package">
                <span class="package-title maya-bday-package">
                    MAYA Birthday Party Package
                </span>
                <span class="package-price">
                    $325.00 + GST
                </span>
            </div>
            <div class="birthday-package-details">
                <strong class="package-days">
                    Time slot choices: Available after 1:00 pm
                </strong>
                <ul class="package-details">
                    <li>
                        2 hours Private Playground Use
                    </li>
                    <li>
                        12 children admission
                    </li>
                    <li>
                        20 adults admission
                    </li>
                    <li>
                        1 large pizza
                    </li>
                    <li>
                        12 juice boxes
                    </li>
                    <li>
                        Birthday sign Decoration
                    </li>
                    <li>
                        Clean Up and Set Up
                    </li>
                    <li>
                        You can bring your own cake
                    </li>
                    <li>
                        You have to provide your own cake plates
                    </li>
                    <li>
                        Additional Child: $12
                    </li>
                    <li>
                        Additional Adult: $5
                    </li>
                    <li>
                        Exceeding time: $20 penalty/15 mins
                    </li>
                </ul>
            </div>
        </div>
        <div class="birthday-package">
            <div class="birthday-package-heading">
                <img class="package-heading-img"
                    src="<?= $this->basePath('images/balloon-chubs.png') ?>"
                    alt="birthday package">
                <span class="package-title off-white cubs-bday-package">
                    CUBS Birthday Party Package
                </span>
                <span class="package-price">
                    $395.00 + GST
                </span>
            </div>
            <div class="birthday-package-details">
                <strong class="package-days">
                    Time slot choices: Available after 1:00 pm
                </strong>
                <ul class="package-details">
                    <li>
                        2.5 Hours Private Playground Use
                    </li>
                    <li>
                        40 people admission (Both Children and Adult) 
                    </li>
                    <li>
                        1 large pizza
                    </li>
                    <li>
                        12 juice boxes + 1 large pot of coffee
                    </li>
                    <li>
                        Mascot Show for 10 minutes
                    </li>
                    <li>
                        Birthday Sign Decoration
                    </li>
                    <li>
                        Clean Up and Set Up
                    </li>
                    <li>
                        You can bring your own cake
                    </li>
                    <li>
                        You have to provide your own cake plates
                    </li>
                    <li>
                        Additional Child: $12
                    </li>
                    <li>
                        Additional Adult: $5
                    </li>
                    <li>
                        Exceeding Time: $20 penalty/15 mins
                    </li>
                </ul>
            </div>
        </div>
        <!-- <div class="options-notif-container off-white">
            DURING COVID-19 SEASON, WE DON'T ALLOW ANY DROP IN CUSTOMERS. PRIVATE BOOKINGS AND
            APPOINTMENTS ONLY.
        </div>
        <div class="options-notif-container off-white">
            PLEASE ASK ABOUT THE OPTIONS FOR FACE PAINTING, BALLOON SCULPTURE OR A CLOWN TO MAKE
            YOUR LITTLE ONES' BIRTHDAY MORE FUN.
        </div> -->
        <!--<div class="options-notif-container off-white">-->
        <!--    Playground is shared with drop-in play customers.-->
        <!--</div>-->
        <div class="options-notif-container off-white">
            PLEASE NOTE (During COVID-19):
            <p class="mt-1 mb-0">
                A. That a 10% deposit is required to secure your booking. Please email transfer the deposit to grizzlycubsden@gmail.com 
            </p>
            <p class="mb-0">
                *All deposit are non-refundable* (waiver is not required to be filled out for this section but will be honored). 
            </p>
            <proc_nice >
                If restrictions are placed back by Government of Alberta due to COVID-19, we would only offer a change of date of event/birthday or credit can be applied towards future use in the playground.
            </p>
            <p class="mt-1">
                B. Soccer station is a separate area and not part of the children's indoor playground use and maybe occupied during your scheduled birthday party.
                If so, please make sure to keep your social distance and wear your masks at all times. 
            </p>
            <p class="mt-1">
                C. All guests are required to sign a waiver and AHS screening questions at the time of their arrival.
            </p>
            <p class="mt-1">
                D. We have an on site cafeteria.
            </p>
            <p>
                Additional food orders can be made via email. Please call <a class="off-white" href="tel:7808160175">7808160175</a>
                for availability or email us at <a class="off-white" href="mailto:grizzlycubsden@gmail.com">grizzlycubsden@gmail.com</a> for booking and menu requests/food orders.
            </p>

        </div>
        
    </div>
</div>
<div class="birthdays-content-container">
    <h2 class="rules-heading text-center">
        Super Goalie Soccer-Themed Birthday Parties
    </h2>
    <div class="birthday-packages-container container">
        <div class="birthday-package">
            <div class="birthday-package-heading">
                <img class="package-heading-img"
                        src="<?= $this->basePath('images/balloon-javs-red.png') ?>"
                        alt="birthday package">
                <span class="package-title">
                    Basic Soccer-Themed Party Package
                </span>
                <span class="package-price">
                    $285.00 + GST
                </span>
            </div>
            <div class="birthday-package-details">
                <strong class="package-days">
                    (Monday to Thursday)    
                </strong>
                <ul class="package-details">
                    <li>
                        Package is for up to 10 people. Every additional person is $15.00 each.
                    </li>
                    <li>
                        60 minutes of Soccer Station + 60 minutes in a party room afterwards
                    </li>
                    <li>
                        Clean Up and Set up
                    </li>
                    <li>
                        Soccer balls provided 
                    </li>
                    <li>
                        Pop or Juice provided
                    </li>
                    <li>
                        2 large Pizzas (24 Slices)
                    </li>
                </ul>
            </div>
        </div>
        <div class="birthday-package">
            <div class="birthday-package-heading">
                <img class="package-heading-img"
                        src="<?= $this->basePath('images/balloon-maya.png') ?>"
                        alt="birthday package">
                <span class="package-title maya-bday-package">
                    Deluxe Soccer-Themed Party Package
                </span>
                <span class="package-price">
                    $325.00 + GST
                </span>
            </div>
            <div class="birthday-package-details">
                <strong class="package-days">
                    (Friday to Sunday + Holidays)    
                </strong>
                <ul class="package-details">
                    <li>
                        Package is for up to 10 people. Every additional person is $15.00 each.
                    </li>
                    <li>
                        60 minutes of Soccer Station + 60 minutes in a party room afterwards
                    </li>
                    <li>
                        Clean Up and Set up
                    </li>
                    <li>
                        Soccer balls provided 
                    </li>
                    <li>
                        Pop or Juice provided
                    </li>
                    <li>
                        2 large Pizzas (24 Slices)
                    </li>
                </ul>
            </div>
        </div>
        <div class="birthday-package">
            <div class="birthday-package-heading">
                <img class="package-heading-img"
                        src="<?= $this->basePath('images/balloon-chubs.png') ?>"
                        alt="birthday package">
                <span class="package-title cubs-bday-package">
                    Premium Soccer-Themed Party Package
                </span>
                <span class="package-price">
                    $425.00 + GST
                </span>
            </div>
            <div class="birthday-package-details">
                <strong class="package-days">
                    (Friday to Sunday + Holidays)    
                </strong>
                <ul class="package-details">
                    <li>
                        Package is for up to 10 people. Every additional person is $15.00 each.
                    </li>
                    <li>
                        60 minutes of Soccer Station + 60 minutes in a party room afterwards
                    </li>
                    <li>
                        Clean Up and Set up
                    </li>
                    <li>
                        Soccer balls provided 
                    </li>
                    <li>
                        Pop or Juice provided
                    </li>
                    <li>
                        3 large Pizzas (36 Slices)
                    </li>
                    <li>
                        2 party Platters of Fries
                    </li>
                    <li>
                        1 fruit platter
                    </li>
                </ul>
            </div>
        </div>
        <div class="options-notif-container off-white">
            Bookings will be private to your party only, and are  a maximum of 15 people.
        </div>
        <div class="options-notif-container off-white">
            <p>
                Depending on Availability Soccer Station Only
            </p>
            <p>
                Rentals are 90.00/hour (5 people included)
            </p>
            <p>
                Please bring your own soccer shoes or runners
            </p>
        </div>
    </div>
</div>
<div class="rules-container">
    <h2 class="rules-heading text-center">
        Birthday Party and Events Rules
    </h2>
    <div class="rule-list-container container">
        <ul class="rule-list">
            <li class="rule-list-item">
                The party deposit is 50% must be paid at the time of booking and is non-refundable.
                The balance must be paid before the end of the party. Parties cancelled over 14 days
                prior to the party date will have their deposit available for transfer to another
                date or for use on future admission. 
            </li>
            <li class="rule-list-item">
                Guests should arrive no earlier than 10 minutes prior to the start of the party or
                event. Parents of the birthday celebrant can come 15 minutes earlier.
            </li>
            <li class="rule-list-item">
                You should leave at the end of your party, but if need to extend time please let the
                front desk know. 
            </li>
            <li class="rule-list-item">
                We encourage booking early and coordinating your needs with us. You can always talk
                to us about time, number of guests that you have, additional food order and time
                extension
            </li>
            <li class="rule-list-item">
                We can also accommodate bigger groups for any events and have the premise only for
                your event for specific hours – please talk to us about this option
            </li>
            <li class="rule-list-item">
                Any inquiries, please call us at
                <a href="tel:7808160175">
                    7808160175
                </a>
                or message us on
                <a href="https://www.facebook.com/grizzlycubsden2019/" target="_blank">
                    FACEBOOK
                </a>
                or email us at
                <a href="mailto:grizzlycubsden@gmail.com">
                    grizzlycubsden@gmail.com
                </a>
            </li>
            
        </ul>
    </div>
</div>
<!-- <div class="contact-form-container">
    <div class="container">
        <h3 id="birthdayForm" class="off-white contact-us-heading">
            TELL US MORE ABOUT YOUR EVENT & WE WILL SEND YOUR PERSONALIZED QUOTE TO YOU SOON!
        </h3>
        <form action="" class="contact-form">
            <div class="form-row contact-form-row">
                <div class="col-md-4 contact-name-field">
                    <input type="text" class="form-control contact-field" placeholder="NAME*" maxlength="30">
                </div>
                <div class="col-md-4 contact-phone-field">
                    <input type="number" class="form-control contact-field" placeholder="PHONE*">
                </div>
                <div class="col-md-4">
                    <input type="email" class="form-control contact-field" placeholder="E-MAIL*">
                </div>
            </div>
            <div class="form-row contact-form-row">
                <div class="col-md-4">
                    <input type="text" class="form-control contact-field" placeholder="PREFERRED DAY*">
                </div>
                <div class="col-md-4">
                    <input type="text" class="form-control contact-field" placeholder="PREFERRED TIME*">
                </div>
                <div class="col-md-4">
                    <input type="number" class="form-control contact-field" placeholder="EXPECTED NO. OF PAX*">
                </div>
            </div>
            <div class="contact-form-row">
                <textarea class="form-control contact-field" placeholder="TELL US MORE ABOUT YOUR EVENT" rows="7">
                </textarea>
            </div>
            <div class="send-btn-container">
                <button type="button" class="send-btn btn"
                    onclick="alert('Site Under Construction')">
                    SEND MESSAGE
                </button>
            </div>
        </form>
    </div>
</div> -->