<?php 
    $this->headTitle('Classes | Grizzly Cubs Den');
?>


<div class="classes-banner-container">
    <div class="container">
        <h2 class="classes-message banner-message">We Offer Fun and High-Quality Classes</h2>
    </div>
</div>
<div class="classes-content-container container">
    <h1 class="classes-heading blue text-center">CLASSES</h1>
    <p class="classes-text">
        Grizzly Cubs Den offers music and dance classes combined! We are a non-competitive,
        high-quality dance education and singing classes for ages 0 – 5 years old with their
        parents. If you are looking for a fun way to stay active and just want to enjoy the laughter
        from your little one, look no further. 
    </p>
    <p class="classes-text">
        We also offer free entrance to our playground after your child’s class for the regular
        members. We offer age-appropriate classes for the ages below: 
    </p>
    <div class="classes-table-container">
        <div class="div-table classes-table">
            <div class="table-heading classes-table-heading">
                <div class="table-row">
                    <div class="table-cell">
                        Classes
                    </div>
                    <div class="table-cell">
                        Age
                    </div>
                </div>
            </div>
            <div class="table-body">
                <div class="table-row">
                    <div class="table-cell">
                        <strong>Honey Bear</strong>
                    </div>
                    <div class="table-cell">
                        <strong>0 - 6 months</strong>
                    </div>
                </div>
                <div class="table-row">
                    <div class="table-cell">
                        <strong>Maya Classes</strong>
                    </div>
                    <div class="table-cell">
                        <strong>7 - 17 months</strong>
                    </div>
                </div>
                <div class="table-row">
                    <div class="table-cell">
                        <strong>JV Classes</strong>
                    </div>
                    <div class="table-cell">
                        <strong>18 - 24 months</strong>
                    </div>
                </div>
                <div class="table-row">
                    <div class="table-cell">
                        <strong>Grizzly Tots</strong>
                    </div>
                    <div class="table-cell">
                        <strong>2 - 3 years</strong>
                    </div>
                </div>
                <div class="table-row">
                    <div class="table-cell">
                        <strong>Cubs Classes</strong>
                    </div>
                    <div class="table-cell">
                        <strong>4 - 5 years</strong>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>