<?php 
    $this->headTitle('Classes | Grizzly Cubs Den');
?>


<!-- <div class="classes-banner-container">
    <div class="container">
        <h2 class="classes-message banner-message">We Offer Fun and High-Quality Classes</h2>
    </div>
</div> -->
<h1 class="classes-heading text-center">
    CLASSES
</h1>
<div class="classes-content-container container">
    <p class="classes-text">
        Grizzly Cubs Den offers different classes for kids. We are non-competitive and seek to be
        instrument of growth and social development for our children. 
    </p>
    <p class="classes-text">
        If you are looking for a fun way for your kids to stay active and just want to enjoy the
        laughter from them, look no further. 
    </p>
    <p class="classes-text">
        We also offer free entrance to our play area after each class for the remaining portion of
        the scheduled play times. Please inquire on being members to get the free pass to the indoor
        playground offered ONLY after each class. 
    </p>
    <div class="classes-table-container">
        <div class="div-table classes-table">
            <div class="table-heading classes-table-heading">
                <div class="table-row">
                    <div class="table-cell">
                        Classes
                    </div>
                    <div class="table-cell">
                        Age
                    </div>
                </div>
            </div>
            <div class="table-body">
                <div class="table-row">
                    <div class="table-cell">
                        <strong>Honey Bear</strong>
                    </div>
                    <div class="table-cell">
                        <strong>0 - 6 months</strong>
                    </div>
                </div>
                <div class="table-row">
                    <div class="table-cell">
                        <strong>Maya Classes</strong>
                    </div>
                    <div class="table-cell">
                        <strong>7 - 17 months</strong>
                    </div>
                </div>
                <div class="table-row">
                    <div class="table-cell">
                        <strong>JV Classes</strong>
                    </div>
                    <div class="table-cell">
                        <strong>18 - 24 months</strong>
                    </div>
                </div>
                <div class="table-row">
                    <div class="table-cell">
                        <strong>Grizzly Tots</strong>
                    </div>
                    <div class="table-cell">
                        <strong>2 - 3 years</strong>
                    </div>
                </div>
                <div class="table-row">
                    <div class="table-cell">
                        <strong>Cubs Classes</strong>
                    </div>
                    <div class="table-cell">
                        <strong>4 - 5 years</strong>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="date-night-container">
        <h2 class="date-night-heading text-center off-white">
            Wednesday Date Night Drop Off
        </h2>
        <div class="dn-content-container container">
            <div class="row">
                <div class="col-md-12">
                    <p class="date-night-text">
                        Catch the latest movie and explore one of the neighbourhood restaurants and enjoy your night
                        out and about. Children will have a fun filled evening with arts, activities, story time,
                        play and more. 
                    </p>
                </div>
                <div class="col-md-12">
                    <div class="date-night-img-container">
                        <!-- <img src="<?=$this->basePath('images/date-night-drop-off.jpg')?>"
                            alt="date night drop off"> -->
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="date-night-details-container">
                        <div class="dn-heading-container off-white">
                            <img class="dn-heading-img"
                                src="<?= $this->basePath('images/balloon-javs-red.png') ?>"
                                alt="birthday package">
                            <span class="dn-details-title off-white">Details</span>
                        </div>
                        <ul class="date-night-details">
                            <li>Every Wednesdays</li>
                            <li>5:15pm - 8:00pm</li>
                            <li>Ages 4 – 7 years old</li>
                            <li>&dollar;45 First Child</li>
                            <li>&dollar;35 Each Additional Sibling</li>
                            <li>Price includes dinner & snacks</li>
                            <li>Children must be potty trained</li>
                            <li>Children must have grippy socks</li>
                            <li>
                                <strong>
                                    Please reserve your spot ahead of time with us by calling 780-816-0175.
                                    Payment required at the time of booking. We are only taking 10-12 kids every week. 
                                </strong>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="date-night-schedule-container">
                        <div class="dn-heading-container off-white">
                            <img class="dn-heading-img"
                                src="<?= $this->basePath('images/balloon-chubs.png') ?>"
                                alt="birthday package">
                            <span class="dn-details-title schedule off-white">Evening Schedule</span>
                        </div>
                        <ul class="date-night-schedule">
                            <li>5:15 – 5:30 – Drop off time</li>
                            <li>5:30 – 5:45 – Guided activities in party room</li>
                            <li>5:45 – 6:30 – Supervised play in our play areas</li>
                            <li>6:30 – 7:00 – Dinner (pizza, fruit, & veggies)</li>
                            <li>7:00 – 7:30 – Arts</li>
                            <li>7:30 – 7:45 – Story Time to wind down</li>
                            <li>7:45 – 8:00 – Get ready for parents pick up </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>