<?php 
    $this->headTitle('Contact Details | Grizzly Cubs Den');
?>

<div class="contact-details-container container">
    <div class="detail-column">
        <img class="detail-img" src="<?= $this->basePath('images/balloon-chubs.png')?>">
        <h2 class="detail-caption">OPERATING HOURS</h2>
        <div class="detail-body">
            <div class="detail-group">
                <div>
                    Monday
                </div>
                <div>
                    Closed
                </div>
            </div>
            <div class="detail-group">
                <div>
                   Tuesday - Friday
                </div>
                <div>
                    10:00am - 5:00pm
                </div>
            </div>
            <div class="detail-group">
                <div>
                   Saturday
                </div>
                <div>
                    10:00am - 6:00pm
                </div>
            </div>
            <div class="detail-group">
                <div>
                   Sunday
                </div>
                <div>
                    11:00am - 5:00pm
                </div>
            </div>
            <div class="detail-group">
                <div>
                    <strong>
                        (Times may still change. No booking necessary. Unlimited playtime.)
                    </strong>
                </div>
            </div>
        </div>
    </div>
    <div class="detail-column">
        <img class="detail-img" src="<?= $this->basePath('images/balloon-javs-red.png')?>">
        <h2 class="detail-caption">EMAIL</h2>
        <div class="detail-body">
            <div class="detail-group">
                <a href="mailto:grizzlycubsden@gmail.com">
                    grizzlycubsden@gmail.com
                </a>
            </div>
        </div>
    </div>
    <div class="detail-column">
        <img class="detail-img" src="<?= $this->basePath('images/balloon-maya.png')?>">
        <h2 class="detail-caption">PHONE</h2>
        <div class="detail-body">
            <div class="detail-group">
                <a href="tel:7808160175">
                    7808160175
                </a>
            </div>
        </div>
    </div>
    <div class="detail-column">
        <img class="detail-img" src="<?= $this->basePath('images/balloon-javs-gray.png')?>">
        <h2 class="detail-caption">ADDRESS</h2>
        <div class="detail-body">
            <div class="detail-group">
                <a href="https://goo.gl/maps/zjg6y5Vjt9gahy6BA" target="_blank">
                    1-5205 50th Ave, Leduc, AB T9E 6T2, Canada
                </a>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="options-notif-container off-white follow-invitation">
        <p>
            SEARCH AND FOLLOW US ON
            <a class="off-white" href="https://www.facebook.com/grizzlycubsden2019/" target="_blank">
                FACEBOOK
            </a> AND
            <a class="off-white" href="https://www.instagram.com/grizzlycubsden/">INSTAGRAM</a> 
            TO GET DAILY AND WEEKLY UPDATES!
        </p>
        <p>
            -Grizzly Cubs Den Indoor Playground and Cafe
        </p>
    </div>
</div>
<div class="contact-form-container">
    <div class="container">
        <h1 class="off-white contact-us-heading">
            GET IN TOUCH
        </h1>
        <form action="" class="contact-form">
            <div class="form-row contact-form-row">
                <div class="col-md-6 contact-name-field">
                    <input type="text" name="name" id="name" class="form-control contact-field"
                        placeholder="NAME" maxlength="35">
                </div>
                <div class="col-md-6">
                    <input type="email" name="email" id="email" class="form-control contact-field"
                        placeholder="E-MAIL" maxlength="35">
                </div>
            </div>
            <div class="contact-form-row">
                <input type="text" name="subject" id="subject" class="form-control contact-field"
                    placeholder="SUBJECT" maxlength="35">
            </div>
            <div class="contact-form-row">
                <textarea id="message" class="form-control contact-field" name="message"
                    placeholder="MESSAGE" rows="7" maxlength="1000"></textarea>
            </div>
            <div class="send-btn-container">
                <button type="button" id="submitContactForm" class="send-btn btn">
                    SEND MESSAGE
                </button>
            </div>
            <div class="contact-us-notification-container">
                <p class="text-center my-2">
                    <span class="contact-us-notification"></span>
                    <a class="contact-us-mail" href="mailto:grizzlycubsden@gmail.com"></a>
                </p>
            </div>
        </form>
    </div>
</div>