<?php 
    $this->headTitle('Facilities | Grizzly Cubs Den');
?>
<div class="operation-hours-container container">
    <h2 class="operation-hours-heading">
        HOURS OF OPERATION
    </h2>
    <div class="operation-hours-content">
        <img class="operation-hours-img" src="<?=$this->basePath('images/hours-line.png')?>" alt="hours of operation">
        <div class="operation-hours">
            <div class="operation-hours-detail">
                <div>
                    Mondays to Thursdays
                </div>
                <div>
                    9:30am - 7:30pm
                </div>
            </div>
            <div class="operation-hours-detail">
                <div>
                   Fridays and Saturdays
                </div>
                <div>
                    9:30am - 7:30pm
                </div>
            </div>
            <div class="operation-hours-detail">
                <div>
                   Sundays and Holidays
                </div>
                <div>
                    9:30am - 6:30pm
                </div>
            </div>
        </div>
    </div>
</div>
<div class="home-carousel-container">
    <h2 class="carousel-heading text-center">
        MY GRIZZLY CUBS KIDS
    </h2>
    <div id="mainHomeCarousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="d-block slide-1 carousel-slide"></div>
            </div>
            <div class="carousel-item">
                <div class="d-block slide-2 carousel-slide"></div>
            </div>
            <div class="carousel-item">
                <div class="d-block slide-3 carousel-slide"></div>
            </div>
            <div class="carousel-item">
                <div class="d-block slide-4 carousel-slide"></div>
            </div>
            <div class="carousel-item">
                <div class="d-block slide-5 carousel-slide"></div>
            </div>
            <div class="carousel-item">
                <div class="d-block slide-6 carousel-slide"></div>
            </div>
            <div class="carousel-item">
                <div class="d-block slide-7 carousel-slide"></div>
            </div>
            <div class="carousel-item">
                <div class="d-block slide-8 carousel-slide"></div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#mainHomeCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#mainHomeCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div id="secondaryCarousel"></div>
</div>