<?php 
    $this->headTitle('Facilities | Grizzly Cubs Den');
?>
<!-- <div class="operation-hours-container container">
    <h2 class="operation-hours-heading">
        HOURS OF OPERATION
    </h2>
    <div class="operation-hours-content">
        <img class="operation-hours-img" src="<?=$this->basePath('images/hours-line.png')?>" alt="hours of operation">
        <div class="operation-hours">
            <div class="operation-hours-detail">
                <div>
                    Mondays to Thursdays
                </div>
                <div>
                    9:30am - 7:30pm
                </div>
            </div>
            <div class="operation-hours-detail">
                <div>
                   Fridays and Saturdays
                </div>
                <div>
                    9:30am - 7:30pm
                </div>
            </div>
            <div class="operation-hours-detail">
                <div>
                   Sundays and Holidays
                </div>
                <div>
                    9:30am - 6:30pm
                </div>
            </div>
        </div>
    </div>
</div> -->
<!-- <div class="cafe-container">
    <h2 class="cafe-heading text-center">
        Cafe
    </h2>
    <div class="cafe-details-container container">
        <div class="menu-container">
            <h3 class="menu-title-container text-center">
                <span class="menu-title">Menu</span>
            </h3>
            <p class="menu-message text-justify red">
                We offer the following food below for Birthday Parties and Events as additional
                orders to your package of choice: 
            </p>
            <ul>
                <li class="menu-item">
                    <div class="item-detail">
                        <span class="item-name">Large Pizza</span>
                        <span class="item-note">(Pepperoni, Cheese, Hawaiian, Vegetarian)</span>
                    </div>
                    <span class="item-price">&dollar;25.95</span>
                </li>
                <li class="menu-item">
                    <div class="item-detail">
                        <span class="item-name">Kids Hotdogs</span>
                    </div>
                    <span class="item-price">&dollar;2.75</span>
                </li>
                <li class="menu-item">
                    <div class="item-detail">
                        <span class="item-name">Chicken Tender Platter</span>
                    </div>
                    <span class="item-price">&dollar;28.99</span>
                </li>
                <li class="menu-item">
                    <div class="item-detail">
                        <span class="item-name">Popcorn Chicken Platter</span>
                    </div>
                    <span class="item-price">&dollar;24.99</span>
                </li>
                <li class="menu-item">
                    <div class="item-detail">
                        <span class="item-name">French Fries Platter</span>
                    </div>
                    <span class="item-price">&dollar;21.00</span>
                </li>
                <li class="menu-item">
                    <div class="item-detail">
                        <span class="item-name">Fruit Platter</span>
                    </div>
                    <span class="item-price">&dollar;35.00</span>
                </li>
                <li class="menu-item">
                    <div class="item-detail">
                        <span class="item-name">Coffee and Tea available upon request for birthday parties</span>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div> -->
<div class="rules-container">
    <h2 class="rules-heading text-center">
        Playground Rules
    </h2>
    <div class="rule-list-container container">
        <ul class="rule-list">
            <li class="rule-list-item">
                NO STROLLERS ARE ALLOWED INSIDE THE PREMISES
            </li>
            <li class="rule-list-item">
                NO SMOKING AND NO ALCOHOL ALLOWED INSIDE THE FACILITY
            </li>
            <li class="rule-list-item">
                Socks must be worn by both parents and children in the playground area. Sorry, no
                shoes or bare feet. Socks can be purchased at the front desk if needed
            </li>
            <li class="rule-list-item">
                Soccer Shoes/cleats or Running Shoes are required at the Soccer Station Area ONLY
                when kicking
            </li>
            <li class="rule-list-item">
                No food, drinks, candy or gums allowed in the play areas. Snacks and beverages must
                be consumed in party room or dining tables
            </li>
            <li class="rule-list-item">
                No sharp objects are allowed in the facility. We kindly ask you to use plastic utensils
            </li>
            <li class="rule-list-item">
                Improper use of toys will result in your child's removal from the playground
            </li>
            <li class="rule-list-item">
                We are not responsible for any loss of or damage to personal property
            </li>
            <li class="rule-list-item">
                We are a nut-free environment. No peanuts or nut products are allowed on the premises.
                Even though we are a nut-free facility, we do not guarantee to be peanut or nut free.
            </li>
            <li class="rule-list-item">
                Please note that children must be 6 years and older for the drop-in service (Please
                inquire on how to register your kids for this service)
            </li>
            <li class="rule-list-item">
                All children must always be accompanied by parent or caregiver
            </li>
            <li class="rule-list-item">
                Certain play areas are restricted by age. Please abide by the age guidelines for
                each play area
            </li>
            <li class="rule-list-item">
                Please keep all the toys in each section where they belong. DO NOT TAKE ANY TOYS HOME.
                WE HAVE SECURITY CAMERAS ALL AROUND AND HIDDEN IN THE AREA
            </li>
            <li class="rule-list-item">
                Please be respectful of everyone inside the facility, specially to fellow parents,
                to all the children and to employees. If there are any concerns, please let the
                management know right away
            </li>
            <li class="rule-list-item">
                Our staff reserves the right to refuse admittance or ask you or your child to leave
                the facility if equipment is used in an improper way or your child is being 
                destructive, disrespectful and causing harm to other children.
            </li>
            <li class="rule-list-item">
                NO CHILDREN WHO ARE ILL ARE ALLOWED INSIDE THE FACILITY. Sorry NO EXCEPTIONS will be
                made when children are unwell as our company’s reputation for hygiene and safety is
                paramount. Children who are unwell during their visit will be kindly asked to leave the
                premises for risk of infection to other patrons.
            </li>
            <li class="rule-list-item">
                Please make sure that the waiver is signed for all the first time comers, before your
                child starts to play
            </li>
            <li class="rule-list-item">
                GRIZZLY CUBS DEN INDOOR PLAYGROUND AND CAFE, and their respective directors, members,
                employees, coaches, volunteers, owners/operators of facilities, and representatives 
                are not responsible for any injury, damage or loss of any kind suffered by a Participant
                during, or as a result of, the soccer sport  or any program, activity or event.
            </li>
        </ul>
    </div>
</div>
<!-- <div class="home-carousel-container">
    <h2 class="carousel-heading text-center">
        MY GRIZZLY CUBS KIDS
    </h2>
    <div id="mainHomeCarousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="d-block slide-1 carousel-slide"></div>
            </div>
            <div class="carousel-item">
                <div class="d-block slide-2 carousel-slide"></div>
            </div>
            <div class="carousel-item">
                <div class="d-block slide-3 carousel-slide"></div>
            </div>
            <div class="carousel-item">
                <div class="d-block slide-4 carousel-slide"></div>
            </div>
            <div class="carousel-item">
                <div class="d-block slide-5 carousel-slide"></div>
            </div>
            <div class="carousel-item">
                <div class="d-block slide-6 carousel-slide"></div>
            </div>
            <div class="carousel-item">
                <div class="d-block slide-7 carousel-slide"></div>
            </div>
            <div class="carousel-item">
                <div class="d-block slide-8 carousel-slide"></div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#mainHomeCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#mainHomeCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div id="secondaryCarousel"></div>
</div> -->