<?php 
    $this->headTitle('Home | Grizzly Cubs Den');
?>

<div class="home-banner-container">
    <div class="container">
        <h1 class="welcome-message banner-message">Welcome to Grizzly Cubs Den</h1>
        <div class="contact-btn-wrapper">
            <button class="contact-btn primary-btn"
                onclick="window.location.href='/contact-us'">
                GET IN TOUCH
            </button>
        </div>
    </div>
</div>
<div class="intro-features-container container">
    <div class="row">
        <div class="about-intro-container col-sm-4">
            <h2 class="about-intro-heading text-center red">
                CHERISH THE MOMENT
            </h2>
            <p class="about-intro-content">
                Grizzly Cubs Den is the latest and most exciting indoor playground in town with various
                elements for the whole family.
            </p>
            <p class="about-intro-content">
                To learn more about us, click on the button below.  
            </p>
            <div class="about-link-wrapper text-center">
                <button class="about-link primary-btn"
                    onclick="window.location.href='/about-us'">
                    ABOUT US
                </button>
            </div>
        </div>
        <div class="features-container col-sm-8">
            <div class="features-row row">
                <div class="feature col-6 col-md-3">
                    <a href="/super-goalie">
                        <div class="feature-img-wrapper">
                            <img class="feature-img" src="<?php echo $this->basePath('images/balloon-chubs.png'); ?>" alt="super goalie">
                        </div>
                        <div class="feature-caption text-center">Super Goalie</div>
                    </a>
                </div>
                <div class="feature col-6 col-md-3">
                    <a href="/classes">
                        <div class="feature-img-wrapper">
                            <img class="feature-img" src="<?php echo $this->basePath('images/balloon-javs-red.png'); ?>" alt="play">
                        </div>
                        <div class="feature-caption text-center">Classes</div>
                    </a>
                </div>
                <div class="feature col-6 col-md-3">
                    <a href="/facilities">
                        <div class="feature-img-wrapper">
                            <img class="feature-img" src="<?php echo $this->basePath('images/balloon-maya.png'); ?>" alt="play">
                        </div>
                        <div class="feature-caption text-center">Play</div>
                    </a>
                </div>
                <div class="feature col-6 col-md-3">
                    <a href="/birthdays">
                        <div class="feature-img-wrapper">
                            <img class="feature-img" src="<?php echo $this->basePath('images/balloon-javs-gray.png'); ?>" alt="birthday">
                        </div>
                        <div class="feature-caption text-center">Birthday</div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="admission-container">
    <h2 class="admission-heading text-center">
        GRIZZLY CUBS DEN ADMISSION
    </h2>
    <div class="admission-details-container container">
        <div class="row">
            <div class="admission-details admission-details-mth col-md-6">
                <div class="mascot-img-container mascot-img-container-left">
                    <img src="<?php echo $this->basePath('images/char-javs.png'); ?>" alt="" class="mascot-img">
                </div>
                <div class="admission-details-table div-table">
                    <div class="table-heading admission-table-heading">
                        <div class="table-row">
                            <div class="table-cell">
                                <div>
                                    Monday - Thursday
                                </div>
                                <div class="table-note">(Excluding Holidays)</div>
                            </div>
                        </div>
                    </div>
                    <div class="table-body">
                        <div class="table-row">
                            <div class="table-cell">
                                <strong>1-11 months</strong>
                            </div>
                            <div class="table-cell">
                                <strong>Free</strong>
                            </div>
                        </div>
                        <div class="table-row">
                            <div class="table-cell">
                                <strong>1-3 years old</strong>
                            </div>
                            <div class="table-cell">
                                <strong>&dollar;8.95</strong>
                            </div>
                        </div>
                        <div class="table-row">
                            <div class="table-cell">
                                <strong>4 yrs old & up</strong>
                            </div>
                            <div class="table-cell">
                                <strong>&dollar;11.95</strong>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="admission-details admission-details-fss col-md-6">
                <div class="admission-details-table div-table">
                    <div class="table-heading admission-table-heading">
                        <div class="table-row">
                            <div class="table-cell">
                                <div>
                                    Friday, Saturday & Sunday
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="table-body">
                        <div class="table-row">
                            <div class="table-cell">
                                <strong>1-11 months</strong>
                            </div>
                            <div class="table-cell">
                                <strong>Free</strong>
                            </div>
                        </div>
                        <div class="table-row">
                            <div class="table-cell">
                                <strong>1-3 years old</strong>
                            </div>
                            <div class="table-cell">
                                <strong>&dollar;10.95</strong>
                            </div>
                        </div>
                        <div class="table-row">
                            <div class="table-cell">
                                <strong>4 yrs old & up</strong>
                            </div>
                            <div class="table-cell">
                                <strong>&dollar;13.95</strong>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="mascot-img-container mascot-img-container-right">
                    <img src="<?php echo $this->basePath('images/char-chubs.png'); ?>" alt="" class="mascot-img">
                </div>
            </div>
        </div>
    </div>
</div>