<?php 
    $this->headTitle('Home | Grizzly Cubs Den Indoor Playground and Café');
?>

<div class="home-banner-container">
    <div class="container">
        <h1 class="welcome-message banner-message">
            Grizzly Cubs Den Indoor Playground and Café
        </h1>
        <div class="contact-btn-wrapper">
            <button class="contact-btn primary-btn"
                onclick="window.location.href='/contact-us'">
                GET IN TOUCH
            </button>
        </div>
    </div>
</div>
<!-- <p class="temporary-heading text-center">
    NOT OPEN YET PLEASE STAND BY FOR GRAND OPENING DATE
</p> -->
<div class="intro-features-container container">
    <div class="row">
        <div class="about-intro-container col-sm-6">
            <h2 class="about-intro-heading text-center red">
                CHERISH THE MOMENT
            </h2>
            <p class="about-intro-content">
                Grizzly Cubs Den is the latest and most exciting indoor playground in town with various
                elements for the whole family.
            </p>
            <p class="about-intro-content">
                To learn more about us, click on the button below.  
            </p>
            <div class="about-link-wrapper text-center">
                <button class="about-link primary-btn"
                    onclick="window.location.href='/about-us'">
                    ABOUT US
                </button>
            </div>
        </div>
        <div class="features-container col-sm-6">
            <div class="features-row row">
                <!-- <div class="feature col-6 col-md-3">
                    <a href="/super-goalie">
                        <div class="feature-img-wrapper">
                            <img class="feature-img"
                                src="<?php echo $this->basePath('images/balloon-chubs.png'); ?>"
                                alt="super goalie">
                        </div>
                        <div class="feature-caption text-center">Super Goalie</div>
                    </a>
                </div>
                <div class="feature col-6 col-md-3">
                    <a href="/classes">
                        <div class="feature-img-wrapper">
                            <img class="feature-img"
                                src="<?php echo $this->basePath('images/balloon-javs-red.png'); ?>"
                                alt="classes">
                        </div>
                        <div class="feature-caption text-center">Classes</div>
                    </a>
                </div> -->
                <div class="feature col-6 col-md-4 offset-md-1">
                    <a href="/facilities">
                        <div class="feature-img-wrapper">
                            <img class="feature-img"
                                src="<?php echo $this->basePath('images/balloon-maya.png'); ?>"
                                alt="play">
                        </div>
                        <div class="feature-caption text-center">Play</div>
                    </a>
                </div>
                <div class="feature col-6 col-md-4 offset-md-2">
                    <a href="/birthdays">
                        <div class="feature-img-wrapper">
                            <img class="feature-img"
                                src="<?php echo $this->basePath('images/balloon-javs-gray.png'); ?>"
                                alt="birthday">
                        </div>
                        <div class="feature-caption text-center">Birthday</div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="admission-container">
    <h2 class="admission-heading text-center">
        Grizzly Cubs Den Admission
    </h2>
    <div class="admission-details-container container">
        <div class="row">
            <div class="admission-details admission-details-mth col-md-6">
                <div class="mascot-img-container mascot-img-container-left">
                    <img src="<?php echo $this->basePath('images/char-javs.png'); ?>"
                        alt="" class="mascot-img">
                </div>
                <div class="admission-details-table div-table">
                    <div class="table-heading admission-table-heading">
                        <div class="table-row">
                            <div class="table-cell">
                                <div>
                                    Monday - Thursday
                                </div>
                                <div class="table-note">(Excluding Holidays)</div>
                            </div>
                        </div>
                    </div>
                    <div class="table-body">
                        <div class="table-row">
                            <div class="table-cell">
                                <strong>0-11 months</strong>
                            </div>
                            <div class="table-cell">
                                <strong>Free</strong>
                            </div>
                        </div>
                        <div class="table-row">
                            <div class="table-cell">
                                <strong>1-9 years</strong>
                            </div>
                            <div class="table-cell">
                                <strong>&dollar;8.95</strong>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="admission-details admission-details-fss col-md-6">
                <div class="admission-details-table div-table">
                    <div class="table-heading admission-table-heading">
                        <div class="table-row">
                            <div class="table-cell">
                                <div>
                                    Friday, Saturday & Sunday
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="table-body">
                        <div class="table-row">
                            <div class="table-cell">
                                <strong>0-11 months</strong>
                            </div>
                            <div class="table-cell">
                                <strong>Free</strong>
                            </div>
                        </div>
                        <div class="table-row">
                            <div class="table-cell">
                                <strong>1-9 years</strong>
                            </div>
                            <div class="table-cell">
                                <strong>&dollar;10.95</strong>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="mascot-img-container mascot-img-container-right">
                    <img src="<?php echo $this->basePath('images/char-chubs.png'); ?>" alt="" class="mascot-img">
                </div>
            </div>
        </div>
        <!-- <div class="guardian-rate-container text-center mt-4">
        </div> -->
        <div class="options-notif-container off-white mt-4">
            <ul class="rates-notif-list"> 
                <li>
                    Only 2 Parents/Guardians are free, every additional guardian  is $4.95
                </li>
                <li>
                    Group of 10 kids or more: 30% off each kid (Discount applies from Monday-Thursday only; Stat Holidays not included)
                </li>
                <li>
                    $5.45 per child (Available Monday-Thursday only; 10am-5pm)
                    Please provide a picture of your FB page, Business Page or any little proof of your dayhome.
                </li>
                <!-- <li>
                    Day care/Day Homes Rate: $5.45 each child (time limited/1.5 hrs limited playtime;
                    Tuesday only 930am-11am & Wednesday at 3pm-430pm; Pre booking Needed; limited spots)
                </li> -->
            </ul>
            <p class="mb-0">
            </p>
            <p>
            </p>
        </div>
    </div>
</div>
<!-- <p class="waiver-heading text-center">
    <a href="#">SIGN OUR WAIVER HERE</a>
</p> -->