<?php 
    $this->headTitle('Super Goalie | Grizzly Cubs Den');
?>


<div class="super-goalie-banner-container">
</div>
<div class="super-goalie-content-container container">
    <div class="sg-content">
        <div class="sg-content-image">
            <img class="sg-image" src="<?php echo $this->basePath('images/super-goalie-1.jpg') ?>" alt="super goalie">
        </div>
        <div class="sg-content-text">
            <p>
                Experience the drama, excitement and emotions of a penalty shootout, as you go
                one-on-one against our supersonic-supergoalie. At Grizzly Cubs Den, it takes a lot 
                more than mere skills to strike the ball to the back of the net.
            </p>
        </div>
    </div>
    <div class="sg-content reversed">
        <div class="sg-content-image">
            <img class="sg-image" src="<?php echo $this->basePath('images/super-goalie-2.jpg') ?>" alt="super goalie">
        </div>
        <div class="sg-content-text">
            <p>
                If you wish to
                score, we suggest you keep calm and wear your lucky football shoes. Our Goalie hates
                losing, how about you?
            </p>
            <p>
                Reserve early to avoid disappointment! Call us now!
            </p>
        </div>
    </div>
    <h1 class="sg-content-heading">
        <strong>
            Super Goalie
        </strong>
    </h1>
    <div class="sg-features-container">
        <div class="sg-feature">
            <div class="sg-feature-img">
                <img src="<?=$this->basePath('images/sg-speed-icon.png')?>" alt="fastest">
            </div>
            <p class="sg-feature-description text-center">
                Can stop the ball up to 235kph.
            </p>
        </div>
        <div class="sg-feature">
            <div class="sg-feature-img">
                <img src="<?=$this->basePath('images/sg-levels-icon.png')?>" alt="levels">
            </div>
            <p class="sg-feature-description">
                Choose to set the number of levels (1 to 3). Default: 3 levels, where 1 being
                beginner and 3 being professional.
            </p>
        </div>
        <div class="sg-feature">
            <div class="sg-feature-img">
                <img src="<?=$this->basePath('images/sg-speed-display-icon.png')?>" alt="speed display">
            </div>
            <p class="sg-feature-description text-center">
                Instant display speed of the ball.
            </p>
        </div>
    </div>
    <div class="sg-prices-container">
        <h2 class="sg-price-heading">
            <strong>
                Prices
            </strong>
        </h2>
        <div class="price-table">
            <div class="table-heading">
                <div class="table-row">
                    <div class="table-cell">
                        6 Penalty Shots
                    </div>
                </div>
            </div>
            <div class="table-body">
                <div class="table-row">
                    <div class="table-cell">Capacity</div>
                    <div class="table-cell">Price</div>
                    <div class="table-cell">Duration</div>
                </div>
                <div class="table-row">
                    <div class="table-cell">Individual Shots</div>
                    <div class="table-cell">&dollar;7.95</div>
                    <div class="table-cell">5 mins slot, maximum of 6 kicks</div>
                </div>
            </div>
        </div>
        <div class="price-table">
            <div class="table-heading">
                <div class="table-row">
                    <div class="table-cell">
                        84 Penalty Shots
                    </div>
                </div>
            </div>
            <div class="table-body">
                <div class="table-row">
                    <div class="table-cell">Capacity</div>
                    <div class="table-cell">Price</div>
                    <div class="table-cell">Duration</div>
                </div>
                <div class="table-row">
                    <div class="table-cell">
                        <ul>
                            <li>group of maximum of 12 people</li>
                            <li>birthdays and corporate events</li>
                        </ul>
                    </div>
                    <div class="table-cell">&dollar;89.95</div>
                    <div class="table-cell">60 mins slot, maximum of 78 kicks</div>
                </div>
            </div>
        </div>
    </div>
</div>