<?php 
    $this->headTitle('Super Goalie | Grizzly Cubs Den');
?>


<div class="super-goalie-banner-container">
</div>
<div class="super-goalie-content-container container">
    <div class="sg-content">
        <div class="sg-content-image">
            <img class="sg-image" src="<?php echo $this->basePath('images/super-goalie-1.jpg') ?>" alt="super goalie">
        </div>
        <div class="sg-content-text">
            <p>
                Experience the drama, excitement and emotions of a penalty shootout, as you go
                one-on-one against our supersonic-supergoalie. At Grizzly Cubs Den, it takes a lot 
                more than mere skills to strike the ball to the back of the net.
            </p>
        </div>
    </div>
    <div class="sg-content reversed">
        <div class="sg-content-image">
            <img class="sg-image" src="<?php echo $this->basePath('images/super-goalie-2.jpg') ?>" alt="super goalie">
        </div>
        <div class="sg-content-text">
            <p>
                If you wish to score, we suggest you keep calm and wear your lucky soccer shoes.
                Our Goalie hates losing, how about you?
            </p>
            <p>
                Reserve early to avoid disappointment!
                <a href="tel:7808160175">
                    Call us now!
                </a>
            </p>
        </div>
    </div>
    <h1 class="sg-content-heading">
        <strong>
            Soccer Super Goalie
        </strong>
    </h1>
    <div class="sg-features-container">
        <!-- <div class="sg-feature">
            <div class="sg-feature-img">
                <img src="<?=$this->basePath('images/sg-speed-icon.png')?>" alt="fastest">
            </div>
            <p class="sg-feature-description text-center">
                Can stop the ball up to 235kph.
            </p>
        </div> -->
        <div class="sg-feature">
            <div class="sg-feature-img">
                <img src="<?=$this->basePath('images/sg-levels-icon.png')?>" alt="levels">
            </div>
            <p class="sg-feature-description">
                Choose to set the number of levels (1 to 3). Default: 3 levels, where 1 being
                beginner and 3 being professional.
            </p>
        </div>
        <div class="sg-feature">
            <div class="sg-feature-img">
                <img src="<?=$this->basePath('images/sg-speed-display-icon.png')?>" alt="speed display">
            </div>
            <p class="sg-feature-description text-center">
                Instant display speed of the ball.
            </p>
        </div>
    </div>
    <div class="sg-prices-container">
        <h2 class="sg-price-heading">
            <strong>
                Prices
            </strong>
        </h2>
        <!-- <div class="price-table">
            <div class="table-heading">
                <div class="table-row">
                    <div class="table-cell">
                        6 Penalty Shots
                    </div>
                </div>
            </div>
            <div class="table-body">
                <div class="table-row">
                    <div class="table-cell">Capacity</div>
                    <div class="table-cell">Price</div>
                    <div class="table-cell">Duration</div>
                </div>
                <div class="table-row">
                    <div class="table-cell">Individual Shots</div>
                    <div class="table-cell">&dollar;7.95</div>
                    <div class="table-cell">5 mins slot, maximum of 6 kicks</div>
                </div>
            </div>
        </div> -->
        <div class="price-table">
            <div class="table-heading">
                <div class="table-row">
                    <div class="table-cell">
                        78 Penalty Shots
                    </div>
                </div>
            </div>
            <div class="table-body">
                <div class="table-row">
                    <div class="table-cell">Capacity</div>
                    <div class="table-cell">Price</div>
                    <div class="table-cell">Duration</div>
                </div>
                <div class="table-row">
                    <div class="table-cell">
                        <ul>
                            <li>group of maximum of 12 people</li>
                            <li>birthdays and corporate events</li>
                        </ul>
                    </div>
                    <div class="table-cell">&dollar;87.95</div>
                    <div class="table-cell">60 mins slot, maximum of 78 kicks</div>
                </div>
            </div>
        </div>
    </div>
</div>
<h2 class="sg-bday-heading text-center">
    <strong>
        Soccer-Themed Birthday Packages
    </strong>
</h2>
<div class="sg-bday-container container">
        <p class="sg-bday-content">
            Soccer Themed Birthday Packages for kids and Teenagers include Soccer Team Penalty Kick
            practice sessions for Individuals who want to never miss a penalty kick again. This is
            where you Come to Celebrate your birthday if you are from Leduc, Beaumont, Devon or
            South Edmonton and anywhere you’re from, you can celebrate with us. For your convenience
            you can book your party online, choose a time frame when you want to be celebrating with
            your friends and family. Always remember that the Birthday celebrant (ONLY) gets a free
            entrance to the indoor playground after the soccer birthday party is over (Depending if
            age 4-10 years old).
        </p>
        <p class="sg-bday-content">
            This is an Incredibly fun and safe environment where you can build memorable moments for
            your kids’ parties.  We are the first Super Goalie in Canada! Come and meet Him and Make
            Your Soccer Dreams come in Reality by practicing against our Super Goalie.
        </p>
    <div class="options-notif-container off-white sg-bday-notif-container">
        <p>
			50% DEPOSIT REQUIRED AT TIME OF BOOKING & NON REFUNDABLE.
		</p>
		<p>
			SOCCER SHOES OR RUNNING SHOES REQUIRED DURING PLAY.
		</p>
		<p>
			YOU CAN BRING YOUR OWN CAKE OR CUPCAKES, BUT NO OTHER OUTSIDE FOOD, DRINK, OR SNACKS
			ARE ALLOWED. WE HAVE A CAFÉ ON SITE.
		</p>
	</div>
    <div class="options-notif-container off-white sg-bday-notif-container">
        <p class="text-underline">
			ADDITIONAL TIME SLOT for the Birthday: You can do an extra 30 Minutes additional Play in
			the Soccer Station for &dollar;43.95 (40 kicks ONLY)
		</p>
	</div>
	<div class="birthday-packages-container container">
        <div class="birthday-package">
            <div class="birthday-package-heading">
                <img class="package-heading-img"
                    src="<?= $this->basePath('images/balloon-javs-red.png') ?>"
                    alt="birthday package">
                <span class="package-title off-white">
					SOCCER BIRTHDAY PARTY PACKAGE 1
                </span>
                <span class="package-price">
                    $285.00 + GST
                </span>
            </div>
            <div class="birthday-package-details">
                <strong class="package-days">
                    (Mondays - Thursdays)    
                </strong>
                <ul class="package-details">
                    <li>
						Entrance for 10 KICKERS for a 60 minute session against our very own goalie
						and Private Use of the Soccer Station for 60 minutes ONLY
					</li>
                    <li>
						90 Minutes Party Table
					</li>
					<li>
						2 (2L) Bottles of Pop or 10 juice boxes
					</li>
					<li>
						2 Large Pizza
					</li>
					<li>
						Set up and Clean Up
					</li>
					<li>
						Additional Kicker ($15.00)
					</li>
					<li>
						Soccer shoes/cleats/indoor running shoes are required when kicking in the
                        soccer area
					</li>
                </ul>
            </div>
        </div>
        <div class="birthday-package">
            <div class="birthday-package-heading">
                <img class="package-heading-img"
                    src="<?= $this->basePath('images/balloon-maya.png') ?>"
                    alt="birthday package">
                <span class="package-title maya-bday-package">
					SOCCER BIRTHDAY PARTY PACKAGE 2
                </span>
                <span class="package-price">
                    $355.00 + GST
                </span>
            </div>
            <div class="birthday-package-details">
                <strong class="package-days">
                    (Fridays - Sundays)    
                </strong>
                <ul class="package-details">
                    <li>
						Entrance for 10 KICKERS for a 60 minute session against our very own goalie
						and Private Use of the Soccer Station for 60 minutes ONLY
					</li>
					<li>
						90 Minutes Party Table
					</li>
					<li>
						2 (2L) Bottles of Pop or 10 juice boxes
					</li>
					<li>
						2 Large Pizza
					</li>
					<li>
						1 Party Platter of Fries
					</li>
					<li>
						Photo time with our Mascot during the Birthday Cake
					</li>
					<li>
						Set Up and Clean Up
					</li>
					<li>
						Additional Kicker ($18.00)
					</li>
					<li>
                        Soccer shoes/cleats/indoor running shoes are required when kicking in the
                        soccer area
					</li>
                </ul>
            </div>
        </div>
        <div class="birthday-package">
            <div class="birthday-package-heading">
                <img class="package-heading-img"
                    src="<?= $this->basePath('images/balloon-chubs.png') ?>"
                    alt="birthday package">
                <span class="package-title off-white cubs-bday-package">
					SOCCER BIRTHDAY PARTY PACKAGE 3
                </span>
                <span class="package-price">
                    $425.00 + GST
                </span>
            </div>
            <div class="birthday-package-details">
                <strong class="package-days">
                    (Fridays - Sundays)    
                </strong>
                <ul class="package-details">
                    <li>
						Entrance for 12 KICKERS for a 60 minute session against our very own goalie
						and Private Use of the Soccer Station for 60 mins only
					</li>
					<li>
						90 Minutes Party Table
					</li>
					<li>
						2 (2L) Bottles of Pop or 10 juice boxes
					</li>
					<li>
						2 Large Pizza
					</li>
					<li>
						2 Party Platter of Fries
					</li>
					<li>
						Photo time with Our Mascot during the Birthday Cake
					</li>
					<li>
						Set Up and Clean Up
					</li>
					<li>
						Additional Kicker ($18.00)
					</li>
					<li>
                        Soccer shoes/cleats/indoor running shoes are required when kicking in the
                        soccer area
					</li>
                </ul>
            </div>
        </div>
        <div class="options-notif-container off-white">
			FOR OTHER EVENTS OR IF YOU WANT TO BOOK YOUR PRIVATE GET TOGETHER WITH FAMILY OR FRIENDS
			OR A DATE NIGHT, PLEASE GIVE US A CALL at 7808160175.
        </div>
    </div>
</div>